theme = "re-terminal"
baseURL = "https://phdpersonalpagetutorial.netlify.app/"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"